export { default as brown } from './brown';
export { default as blue } from './blue';
export { default as beige } from './beige';
export { default as grey } from './grey';
export { default as dark } from './dark';

// User
export const deepBlue = "#113883";
export const pastelPink = "#FFF0E2";
export const green = "#0E603F";
export const babyBlue = "#F4F6FA";
export const yellow = "#FFC134";
export const muted = "#C2D2F0";
export const mutedGrey = "#CCCCCC";
export const enabled = "#955F43";
export const royablBlue = "#6981B0";
export const darkRoyalBlue = "#303268";
export const transparency = "#FFF6EE";
export const pink = "#CC7474";
export const red = "#973C09";
export const orange = "#FBA24F";
export const blueNight = "#0516";
export const lightGreen = "#6EAB8A";
export const kingBlue = "#0F2B54";
export const cream = "#F4F4F4";
export const lightGrey = "#989898";
export const placeholder = "#8B8B8B";
export const darkGrey = "#666666";
export const lightBlue = "#B9D3EF";
export const darkBlue = "#1F5693";
export const lightYellow = "#FCF3D8";
export const darkYellow = "#EBC351";
export const lightPurple = "#E1DCFA";
export const darkPurple = "#8A7EBE";
export const lightRed = "#FDE7E6";
export const darkRed = "#D16D6A";
export const textGrey = "#979797";
export const descriptionGrey = "#7A7A7A";
export const welcomeBlue = "#4E5F81";
export const iconGrey = "#606060";
export const bgGrey = "#BBC4D7";
export const otherGrey = "#0F0E0E";
export const navbarBlue = "#566571";
export const navbarBg = "#D9D9D9";
export const cellBlue = "#7A8F9E";
export const lightestGrey = "#E9E5DB";
export const basicGrey = "#FBF9F9";
export const redBrown = "#520202a1";
export const redBrownDark = "#520202b3";

// ADMIN
export const darkestOrange = "#FF5833";
export const lightestGreen ="#ADE783";
export const darkestYellow = "#FCC455";
export const darkNight = "#37404E";
export const darkerBlue = "#0E203A";
export const lightestBlue = "#DEE6F6";
export const darkBrown = "#53371E";
export const darkOrange ="#FBA24F";